"""
app.py
Streamlit UI for Diagnoscan.
All model/LLM logic lives in engine.py — this file only handles presentation.
"""

import streamlit as st
from PIL import Image
from engine import MODEL_CONFIG, analyze_image

st.set_page_config(
    page_title="Diagnoscan",
    page_icon="🩺",
    layout="centered",
)

# ---------------------------------------------------------------------------
# Minimal custom styling
# ---------------------------------------------------------------------------
st.markdown(
    """
    <style>
    .main-title {
        font-size: 2.2rem;
        font-weight: 700;
        margin-bottom: 0;
    }
    .subtitle {
        color: #6b7280;
        margin-top: 0;
        margin-bottom: 1.5rem;
    }
    .credit-badge {
        position: fixed;
        bottom: 12px;
        right: 16px;
        background: rgba(0,0,0,0.06);
        padding: 4px 10px;
        border-radius: 8px;
        font-size: 0.75rem;
        color: #6b7280;
        z-index: 100;
    }
    .result-card {
        padding: 1rem 1.2rem;
        border-radius: 10px;
        background: #f8fafc;
        border: 1px solid #e2e8f0;
        margin-top: 1rem;
    }
    </style>
    <div class="credit-badge">Developed by Umer Farooq</div>
    """,
    unsafe_allow_html=True,
)

# ---------------------------------------------------------------------------
# Header
# ---------------------------------------------------------------------------
st.markdown('<p class="main-title">🩺 Diagnoscan</p>', unsafe_allow_html=True)
st.markdown(
    '<p class="subtitle">Diagnoscan — AI-assisted medical imaging analysis (educational demo)</p>',
    unsafe_allow_html=True,
)

st.warning(
    "⚠️ **This is an educational demo, not a diagnostic tool.** "
    "Results are generated by a machine learning model and should never replace "
    "professional medical evaluation. Always consult a qualified healthcare provider."
)

# ---------------------------------------------------------------------------
# Input controls
# ---------------------------------------------------------------------------
disease_key = st.selectbox("Select scan type", list(MODEL_CONFIG.keys()))

uploaded_file = st.file_uploader(
    "Upload an image", type=["jpg", "jpeg", "png"], accept_multiple_files=False
)

analyze_clicked = st.button("Analyze", type="primary", disabled=uploaded_file is None)

# ---------------------------------------------------------------------------
# Run analysis
# ---------------------------------------------------------------------------
if uploaded_file is not None:
    image = Image.open(uploaded_file)
    st.image(image, caption="Uploaded image", width=320)

if analyze_clicked and uploaded_file is not None:
    with st.spinner("Analyzing image and generating explanation..."):
        try:
            result = analyze_image(disease_key, image)
        except FileNotFoundError:
            st.error(
                f"Model file for '{disease_key}' not found. "
                "Make sure the corresponding .pt file is in the models/ folder."
            )
            st.stop()
        except Exception as e:
            st.error(f"Something went wrong during analysis: {e}")
            st.stop()

    prediction = result["prediction"]
    explanation = result["explanation"]

    st.markdown('<div class="result-card">', unsafe_allow_html=True)
    st.subheader(f"Prediction: {prediction['predicted_class_display']}")
    st.write(f"**Confidence:** {prediction['confidence']}%")

    with st.expander("Full probability breakdown"):
        for cls, pct in sorted(
            prediction["all_probabilities"].items(), key=lambda x: -x[1]
        ):
            st.write(f"{cls}: {pct}%")
            st.progress(min(int(pct), 100))
    st.markdown("</div>", unsafe_allow_html=True)

    st.subheader("What this means")
    st.write(explanation)

    st.caption(
        "This explanation was generated by an AI language model based on the "
        "prediction above. It is informational only and not a medical diagnosis."
    )
